### ISSUE TITLE
Reading hdf5 files

### ISSUE THREAD

**Issue by robertahunt** [zahrag/BIOSCAN-1M#3]
Hello,

Thanks a lot for making the dataset available. I'm really looking forward to trying to work with it. 

I have just started looking at the data and am having trouble reading the images from cropped_256.hdf5. Perhaps this is just due to my own unfamiliarity with hdf5, but it seems like the images are 1 dimensional and that dimension does not seem necessarily divisible by 256. 

I am reading the images in as follows:

```import h5py
import numpy as np

with h5py.File('cropped_256.hdf5','r+') as hdf5:
    img = np.array(hdf5['bioscan_dataset']['3652597.jpg'])
    print(img.shape)
    print(img.shape / 256)
```
and I get the following output:

> (7633,)
> 29.81640625

I have tried with a few different images and I get similar results. For now I'll use the zip files so this probably isn't a barrier for many, but if I am doing something wrong in the reading of the hdf5 data, maybe a how-to in the readme would be a good idea.

Thanks again for the dataset!

**Comment by zahrag** [comment]
Hi,

Please use the utilts.py from code repository, and the function which reads from hdf5 file.
Below is a sample code, adjust it accordingly.

file_name = 'path_to_hdf5_file/cropped_256.hdf5'
hdf5 = h5py.File(file_name, 'r')
hdf5_dataset = hdf5['bioscan_dataset']
image_names = list(hdf5_dataset.keys())
for img_name in image_names:
    image = read_from_hdf5(hdf5_dataset, img_name, saved_as_binary=True)
    image.show()



Best
/Zahra

----------------------
Zahra Gharaee
Postdoctoral Research Fellow
Vision and Image ​Processing Lab
East Campus (EC4),University of Waterloo
200 University Avenue West
Waterloo, ON, Canada N2L 3G1

________________________________
From: Roberta Hunt ***@***.***>
Sent: Friday, September 29, 2023 7:31 AM
To: zahrag/BIOSCAN-1M ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [zahrag/BIOSCAN-1M] Reading hdf5 files (Issue #3)


Hello,

Thanks a lot for making the dataset available. I'm really looking forward to trying to work with it.

I have just started looking at the data and am having trouble reading the images from cropped_256.hdf5. Perhaps this is just due to my own unfamiliarity with hdf5, but it seems like the images are 1 dimensional and that dimension does not seem necessarily divisible by 256.

I am reading the images in as follows:

import numpy as np

with h5py.File('cropped_256.hdf5','r+') as hdf5:
    img = np.array(hdf5['bioscan_dataset']['3652597.jpg'])
    print(img.shape)
    print(img.shape / 256)


and I get the following output:

(7633,)
29.81640625

I have tried with a few different images and I get similar results. For now I'll use the zip files so this probably isn't a barrier for many, but if I am doing something wrong in the reading of the hdf5 data, maybe a how-to in the readme would be a good idea.

Thanks again for the dataset!

**Comment by robertahunt** [comment]
Works like a charm. Thanks so much for sorting that out!
